### ISSUE TITLE
sus

### ISSUE THREAD

**Issue by duck123acb** [hephaestushex/spearRun#1]
impartiality sus

**Comment by hephaestushex** [comment]
yes, pretty sus

**Comment by duck123acb** [comment]
me after 1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste1. are made of cells

2. require energy

3. Respond and adapt to the environment

4. reproduce

5. Grow and Develop

6. Produce Waste
